/**
 * The three importable entities. Pure data — see lib/import/spec.ts for the
 * engine. Aliases are in normalized form (see normalizeHeader): lowercase,
 * snake_case, parentheticals dropped. Spec order = matching precedence.
 */

import type { FieldDef, ImportEntity, ImportSpec } from "./spec";

const PAYMENT_TERMS_VALUES: Record<string, string> = {
  cod: "cod",
  cash_on_delivery: "cod",
  due_on_receipt: "due_on_receipt",
  due_upon_receipt: "due_on_receipt",
  upon_receipt: "due_on_receipt",
  on_receipt: "due_on_receipt",
  immediate: "due_on_receipt",
  prepaid: "due_on_receipt",
  net_15: "net_15",
  net15: "net_15",
  n15: "net_15",
  "15": "net_15",
  net_30: "net_30",
  net30: "net_30",
  n30: "net_30",
  "30": "net_30",
  net_60: "net_60",
  net60: "net_60",
  n60: "net_60",
  "60": "net_60",
  net_90: "net_90",
  net90: "net_90",
  n90: "net_90",
  "90": "net_90",
};
const PAYMENT_TERMS_ALLOWED = [
  "COD",
  "Due on receipt",
  "Net 15",
  "Net 30",
  "Net 60",
  "Net 90",
];

const ADDRESS_FIELDS: FieldDef[] = [
  {
    key: "address_line1",
    label: "Address line 1",
    aliases: ["address", "address_1", "address1", "street", "street_address"],
    hint: "Street address",
    example: "120 Industrial Way",
  },
  {
    key: "address_line2",
    label: "Address line 2",
    aliases: ["address_2", "address2", "suite", "unit", "apt"],
    hint: "Suite / unit",
    example: "Suite B",
  },
  {
    key: "city",
    label: "City",
    aliases: ["town"],
    hint: "",
    example: "Atlanta",
  },
  {
    key: "state",
    label: "State",
    aliases: ["province", "region", "state_province"],
    hint: "Two-letter code or full name",
    example: "GA",
  },
  {
    key: "zip",
    label: "ZIP",
    aliases: ["postal_code", "zip_code", "postcode", "postal", "zipcode"],
    hint: "",
    example: "30309",
  },
  {
    key: "country",
    label: "Country",
    hint: "Defaults to US",
    example: "US",
  },
];

export const PRODUCT_SPEC: ImportSpec = {
  entity: "products",
  label: "products",
  singular: "product",
  keyField: "barcode",
  keyLabel: "barcode",
  keyFallback: "internal_sku",
  fields: [
    {
      key: "barcode",
      label: "Barcode",
      required: true,
      aliases: [
        "upc",
        "ean",
        "gtin",
        "upc_ean",
        "barcode_upc",
        "product_code",
        "item_code",
        "item_number",
        "item_no",
        "part_number",
        "part_no",
        "code",
      ],
      hint: "UPC, EAN, or your own code. If you only have a SKU column, we use it as the barcode.",
      example: "0123456789012",
      maxLength: 120,
    },
    {
      key: "name",
      label: "Name",
      required: true,
      aliases: [
        "product_name",
        "product",
        "item_name",
        "title",
        "product_title",
        "item",
        "description",
      ],
      hint: "Display name",
      example: "White Oak Plank 7in",
      maxLength: 255,
    },
    {
      key: "internal_sku",
      label: "Internal SKU",
      aliases: ["sku", "item_sku", "sku_code", "product_sku", "internal_code"],
      hint: "Your own SKU; must be unique",
      example: "WO-PLK-7",
      maxLength: 120,
    },
    {
      key: "category",
      label: "Category",
      aliases: [
        "category_name",
        "product_category",
        "product_type",
        "type",
        "department",
        "group",
        "collection",
      ],
      hint: "Matched by name, created if new",
      example: "Hardwood",
      maxLength: 120,
    },
    {
      key: "manufacturer",
      label: "Manufacturer",
      aliases: ["brand", "make", "maker", "mfr", "mfg", "manufacturer_name"],
      hint: "Brand / maker",
      example: "Acme Flooring",
      maxLength: 255,
    },
    {
      key: "quantity",
      label: "Quantity on hand",
      kind: "int",
      aliases: [
        "qty",
        "on_hand",
        "quantity_on_hand",
        "qty_on_hand",
        "stock",
        "stock_qty",
        "stock_quantity",
        "in_stock",
        "inventory",
        "count",
        "units",
        "available",
      ],
      hint: "Initial stock for NEW products (ignored for existing ones). Goes to the holding area unless a location is given.",
      example: "48",
      max: 10_000_000,
    },
    {
      key: "location",
      label: "Location",
      aliases: [
        "bin",
        "bin_location",
        "slot",
        "shelf",
        "storage_location",
        "position",
        "loc",
      ],
      hint: "SECTION-BAY-LEVEL in your facility, e.g. A-3-2. Blank = holding area.",
      example: "A-3-2",
      maxLength: 40,
    },
    {
      key: "unit_cost",
      label: "Unit cost",
      kind: "money",
      aliases: [
        "cost",
        "cost_price",
        "purchase_price",
        "buy_price",
        "cost_per_unit",
        "unit_cost_usd",
        "cogs",
      ],
      hint: "What you pay per unit — powers valuation and reorder math",
      example: "18.50",
    },
    {
      key: "unit_price",
      label: "Unit price",
      kind: "money",
      aliases: [
        "price",
        "sell_price",
        "sale_price",
        "retail",
        "retail_price",
        "list_price",
        "msrp",
      ],
      hint: "What you sell it for",
      example: "32.00",
    },
    {
      key: "reorder_point",
      label: "Reorder point",
      kind: "int",
      aliases: [
        "reorder",
        "reorder_level",
        "reorder_at",
        "min",
        "minimum",
        "min_qty",
        "min_stock",
        "par",
        "par_level",
        "low_stock_threshold",
      ],
      hint: "Flag as low when on-hand falls to this; default 0",
      example: "20",
      max: 10_000_000,
    },
    {
      key: "safety_stock",
      label: "Safety stock",
      kind: "int",
      aliases: ["safety", "buffer", "buffer_stock"],
      hint: "Buffer kept above the reorder point; default 0",
      example: "5",
      max: 10_000_000,
    },
    {
      key: "lead_time_days",
      label: "Lead time (days)",
      kind: "int",
      aliases: ["lead_time", "lead_days", "supplier_lead_time", "lead"],
      hint: "Days from order to delivery",
      example: "14",
      max: 3650,
    },
    {
      key: "supplier",
      label: "Preferred supplier",
      aliases: [
        "vendor",
        "preferred_supplier",
        "supplier_name",
        "vendor_name",
        "preferred_vendor",
      ],
      hint: "Matched by name, created if new",
      example: "Acme Flooring Supply",
      maxLength: 255,
    },
    {
      key: "dimensions",
      label: "Dimensions",
      aliases: ["size", "dims", "dimension", "measurements"],
      hint: "Free-form, e.g. 48x7x0.75 in",
      example: "48x7x0.75 in",
      maxLength: 120,
    },
    {
      key: "weight",
      label: "Weight",
      aliases: ["wt", "unit_weight", "weight_lb", "weight_kg"],
      hint: "Free-form, e.g. 2.4 lb",
      example: "2.4 lb",
      maxLength: 60,
    },
    {
      key: "notes",
      label: "Notes",
      aliases: ["note", "comments", "comment", "remarks", "memo"],
      hint: "Free-form",
      example: "Matte finish",
      maxLength: 2000,
    },
  ],
};

export const SUPPLIER_SPEC: ImportSpec = {
  entity: "suppliers",
  label: "suppliers",
  singular: "supplier",
  keyField: "name",
  keyLabel: "name",
  keyCaseInsensitive: true,
  fields: [
    {
      key: "name",
      label: "Name",
      required: true,
      aliases: [
        "supplier",
        "supplier_name",
        "vendor",
        "vendor_name",
        "company",
        "company_name",
      ],
      hint: "Company name; must be unique",
      example: "Acme Flooring Supply",
      maxLength: 200,
    },
    {
      key: "contact_name",
      label: "Contact name",
      aliases: ["contact", "contact_person", "rep", "attn", "attention"],
      hint: "Your rep",
      example: "Dana Whitfield",
      maxLength: 200,
    },
    {
      key: "email",
      label: "Email",
      kind: "email",
      aliases: ["email_address", "e_mail", "contact_email"],
      hint: "Order confirmations go here",
      example: "orders@acmeflooring.com",
      maxLength: 254,
    },
    {
      key: "phone",
      label: "Phone",
      aliases: ["telephone", "phone_number", "tel", "mobile", "contact_phone"],
      hint: "",
      example: "(404) 555-0142",
      maxLength: 40,
    },
    {
      key: "website",
      label: "Website",
      aliases: ["url", "web", "site"],
      hint: "",
      example: "https://acmeflooring.com",
      maxLength: 255,
    },
    ...ADDRESS_FIELDS,
    {
      key: "tax_id",
      label: "Tax ID",
      aliases: ["ein", "vat", "vat_number", "tax_number"],
      hint: "",
      example: "58-1234567",
      maxLength: 60,
    },
    {
      key: "account_number",
      label: "Account number",
      aliases: ["account", "account_no", "acct", "customer_number", "our_account"],
      hint: "Your account with them",
      example: "AC-10422",
      maxLength: 80,
    },
    {
      key: "payment_terms",
      label: "Payment terms",
      kind: "enum",
      aliases: ["terms", "payment_term", "term"],
      values: PAYMENT_TERMS_VALUES,
      allowed: PAYMENT_TERMS_ALLOWED,
      hint: "COD, Due on receipt, Net 15/30/60/90; default Net 30",
      example: "Net 30",
    },
    {
      key: "default_lead_time_days",
      label: "Lead time (days)",
      kind: "int",
      aliases: ["lead_time", "lead_time_days", "lead_days", "lead"],
      hint: "Typical days from PO to delivery",
      example: "10",
      max: 3650,
    },
    {
      key: "notes",
      label: "Notes",
      aliases: ["note", "comments", "comment", "remarks", "memo"],
      hint: "Free-form",
      example: "Ships Mon/Thu",
      maxLength: 2000,
    },
  ],
};

export const CUSTOMER_SPEC: ImportSpec = {
  entity: "customers",
  label: "customers",
  singular: "customer",
  keyField: "name",
  keyLabel: "name",
  keyCaseInsensitive: true,
  fields: [
    {
      key: "name",
      label: "Name",
      required: true,
      aliases: [
        "customer",
        "customer_name",
        "contact",
        "contact_name",
        "full_name",
        "client",
      ],
      hint: "Person or account name; must be unique",
      example: "Priya Raman",
      maxLength: 200,
    },
    {
      key: "company_name",
      label: "Company",
      aliases: ["company", "business", "business_name", "organization", "org"],
      hint: "Filling this in makes the customer a business",
      example: "Raman Interiors LLC",
      maxLength: 200,
    },
    {
      key: "customer_type",
      label: "Type",
      kind: "enum",
      aliases: ["type", "kind", "segment"],
      values: {
        individual: "individual",
        person: "individual",
        consumer: "individual",
        retail: "individual",
        residential: "individual",
        b2c: "individual",
        business: "business",
        company: "business",
        commercial: "business",
        wholesale: "business",
        contractor: "business",
        trade: "business",
        b2b: "business",
      },
      allowed: ["individual", "business"],
      hint: "individual or business; inferred from Company when blank",
      example: "business",
    },
    {
      key: "email",
      label: "Email",
      kind: "email",
      aliases: ["email_address", "e_mail", "contact_email"],
      hint: "",
      example: "priya@ramaninteriors.com",
      maxLength: 254,
    },
    {
      key: "phone",
      label: "Phone",
      aliases: ["telephone", "phone_number", "tel", "mobile", "contact_phone"],
      hint: "",
      example: "(404) 555-0199",
      maxLength: 40,
    },
    ...ADDRESS_FIELDS,
    {
      key: "tax_id",
      label: "Tax ID",
      aliases: ["ein", "vat", "vat_number", "tax_number", "resale_number"],
      hint: "",
      example: "",
      maxLength: 60,
    },
    {
      key: "credit_limit",
      label: "Credit limit",
      kind: "money",
      aliases: ["credit", "limit"],
      hint: "",
      example: "5000",
    },
    {
      key: "payment_terms",
      label: "Payment terms",
      kind: "enum",
      aliases: ["terms", "payment_term", "term"],
      values: PAYMENT_TERMS_VALUES,
      allowed: PAYMENT_TERMS_ALLOWED,
      hint: "COD, Due on receipt, Net 15/30/60/90; default Net 30",
      example: "Net 30",
    },
    {
      key: "discount_percent",
      label: "Discount %",
      kind: "percent",
      aliases: ["discount", "discount_pct", "trade_discount"],
      hint: "0–100; default 0",
      example: "10",
    },
    {
      key: "notes",
      label: "Notes",
      aliases: ["note", "comments", "comment", "remarks", "memo"],
      hint: "Free-form",
      example: "Prefers Saturday pickups",
      maxLength: 2000,
    },
  ],
};

export const IMPORT_SPECS: Record<ImportEntity, ImportSpec> = {
  products: PRODUCT_SPEC,
  suppliers: SUPPLIER_SPEC,
  customers: CUSTOMER_SPEC,
};

export function isImportEntity(v: unknown): v is ImportEntity {
  return v === "products" || v === "suppliers" || v === "customers";
}
